### ISSUE TITLE
Is the latest release of ddrbin 1.16 still causing problems?

### ISSUE THREAD

**Issue by farwayer** [7Ji/orangepi5-rkloader#3]
First of all big thanks for the work.

ddrbin was updated to v1.16 two months age. Maybe you have already checked whether the problems that you described for version v1.13 have gone away with the new version?

**Comment by 7Ji** [comment]
> ddrbin was updated to v1.16 two months age

Thanks for the reminder.

> Maybe you have already checked whether the problems that you described for version v1.13 have gone away with the new version?

Sorry but I haven't and couldn't. I'm using my opi 5 plus on which the ddr issue was found as the build server for my archrepo so I don't want to risk taking down the repo builder with it, and I'm on my short holiday away from my opi 5 plus.

**Comment by farwayer** [comment]
Ok, thanks. Maybe I will try when I have some free time. What were the problems with previous versions? Just so I know what to look out for. Or maybe a newsletter/issue where I can read about it?

**Comment by 7Ji** [comment]
It would cause random memory issues, including but not limited to:
 - The board won't pass SPL when using mainline u-boot, it won't even start
 - An application would crash if it writes to broken memory area
 - The kernel would panic and report a traceback that's different every time, complaining about some trustworthy kernel modules.

Even if you could boot into the system, a manual memory write loop would result in either the above issue 2 or issue 3:
```
while true; do cat /dev/random > /tmp/testfile; rm /tmp/testfile; done
```

**Comment by 7Ji** [comment]
I've removed the locking, v1.16 should be used in the next build.
