### ISSUE TITLE
orangepi-5-pro

### ISSUE THREAD

**Issue by Callyth** [7Ji/orangepi5-rkloader#4]
Hi there, this code is very readable. It seems like rkloader.sh builds `orangepi-xunlong/u-boot-orangepi` and combines it with bl31 and DDR. I only changed the part of `configs_vendor=(${configs_vendor:-orangepi_5b orangepi_5 orangepi_5_plus orangepi_5_sata})` to include `orangepi_5_pro` and tried building, but it gets stuck at the part where u-boot is loaded.
```
DDR 9fffbe1e78 cym 24/02/04-10:09:20,fwver: v1.16
LPDDR5, 2400MHz
channel[0] BW=16 Col=10 Bk=16 CS0 Row=16 CS1 Row=16 CS=2 Die BW=16 Size=4096MB
channel[1] BW=16 Col=10 Bk=16 CS0 Row=16 CS1 Row=16 CS=2 Die BW=16 Size=4096MB
channel[2] BW=16 Col=10 Bk=16 CS0 Row=16 CS1 Row=16 CS=2 Die BW=16 Size=4096MB
channel[3] BW=16 Col=10 Bk=16 CS0 Row=16 CS1 Row=16 CS=2 Die BW=16 Size=4096MB
Manufacturer ID:0xff
CH0 RX Vref:27.5%, TX Vref:20.0%,19.0%
CH1 RX Vref:27.9%, TX Vref:22.0%,21.0%
CH2 RX Vref:25.4%, TX Vref:18.0%,19.0%
CH3 RX Vref:26.7%, TX Vref:21.0%,21.0%
change to F1: 534MHz
change to F2: 1320MHz
change to F3: 1968MHz
change to F0: 2400MHz
out
U-Boot SPL board init
U-Boot SPL 2017.09 (Jul 27 2024 - 11:08:20)
unknown raw ID 0 0 0
unrecognized JEDEC id bytes: 00, 00, 00
Trying to boot from MMC1
Trying fit image at 0x400 sector
## Verified-boot: 0
## Checking uboot 0x00200000 ... sha256(8e22900105...) + OK
## Checking fdt 0x0034af20 ... sha256(1b12611ccd...) + OK
Total: 183.646 ms

Jumping to U-Boot(0x00200000)
```
DDR and bl31 should be usable as they are, so they shouldn't be the cause. What could be the cause?

**Comment by 7Ji** [comment]
```
Trying fit image at 0x400 sector
## Verified-boot: 0
## Checking uboot 0x00200000 ... sha256(8e22900105...) + OK
## Checking fdt 0x0034af20 ... sha256(1b12611ccd...) + OK
Total: 183.646 ms
```

is not right, on RK3588 before jumping to u-boot, earlier BL stages need to perform DDR training and other stuffs. On my boards (5 and 5plus) there're more components here to verify.

And the earlier log shows exactly this:

```
unknown raw ID 0 0 0
unrecognized JEDEC id bytes: 00, 00, 00
```

This means the DDR blob is not compatible with the actual onboard DDR chips

**Comment by Callyth** [comment]
> is not right, on RK3588 before jumping to u-boot, earlier BL stages need to perform DDR training and other stuffs. On my boards (5 and 5plus) there're more components here to verify.

Yes, but the DDR error doesn't seem to affect the loading of U-Boot itself.

Bootloader where U-Boot is not loaded:
```
Checking uboot 0x00200000 ... sha256(4b20a5b033...) + OK
Checking fdt 0x0034af20 ... sha256(1b12611ccd...) + OK
Jumping to U-Boot(0x00200000)
```
Bootloader where U-Boot is loaded:
```
Checking atf-1 0x00040000 ... sha256(a7d1d8d191...) + OK
Checking uboot 0x00200000 ... sha256(c135d3f369...) + OK
Checking fdt 0x0034af18 ... sha256(bcb1d629f4...) + OK
Checking atf-2 0xff100000 ... sha256(4b2065349b...) + OK
Checking atf-3 0x000f0000 ... sha256(aa71013e72...) + OK
Jumping to U-Boot(0x00200000) via ARM Trusted Firmware(0x00040000)
```
The difference seems to be that atf-1 to atf-3 are recognized and `via ARM Trusted Firmware(0x00040000)` is added.
Could it be that bl31 is not being loaded correctly?

**Comment by 7Ji** [comment]
Can you confirm that all other profiles were built successfully? And were all components built successfully? There was a trap in building u-boot for RK devices that it would report build success even though a part of it failed, returning 0 for make. The broken stuff was RK prop ATF building tool if I remember correctly, due to broken cross compiler. What is your build environment? Was it Arch? Did you install system cross-compiler?

**Comment by 7Ji** [comment]
Can you try this image I built locally?

[rkloader-vendor-v2017.09-rk3588-orangepi_5_pro-r34.8a8fd7b0-bl31-v1.45-ddr-v1.16.img.gz](https://github.com/user-attachments/files/16408554/rkloader-vendor-v2017.09-rk3588-orangepi_5_pro-r34.8a8fd7b0-bl31-v1.45-ddr-v1.16.img.gz)

Edit: Seems vendor image built on Arch is broken, the image from a same build run on my Arch desktop for 5 was broken, but the automatical build here is OK. I need to dig on why that's the case.

**Comment by 7Ji** [comment]
Nailed it, you need python2:
```
./"arch/arm/mach-rockchip/make_fit_atf.sh" \
arch/arm/dts/rk3588s-orangepi-5.dtb > u-boot.its
  UPD     include/generated/timestamp_autogenerated.h
/usr/bin/env: 'python2': No such file or directory
ls: cannot access 'bl31_0x*.bin': No such file or directory
  CHK     include/generated/version_autogenerated.h
  CHK     include/generated/generic-asm-offsets.h
  CHK     include/generated/asm-offsets.h
```
RK's script ignores the error so u-boot build appears to be OK, but the result image is actually broken due to failed atf building

Please check the following image, it came from the same build of vendor u-boot images that I verified to work on my 5.

[rkloader-vendor-v2017.09-rk3588-orangepi_5_pro-r34.8a8fd7b0-bl31-v1.45-ddr-v1.16.img.gz](https://github.com/user-attachments/files/16409091/rkloader-vendor-v2017.09-rk3588-orangepi_5_pro-r34.8a8fd7b0-bl31-v1.45-ddr-v1.16.img.gz)

**Comment by 7Ji** [comment]
Closed by https://github.com/7Ji/orangepi5-rkloader/commit/e659ca2ad3ba562b23d4074b3b740e9986dd1943

**Comment by Callyth** [comment]
> Please check the following image, it came from the same build of vendor u-boot images that I verified to work on my 5.
> 
> [rkloader-vendor-v2017.09-rk3588-orangepi_5_pro-r34.8a8fd7b0-bl31-v1.45-ddr-v1.16.img.gz](https://github.com/user-attachments/files/16409091/rkloader-vendor-v2017.09-rk3588-orangepi_5_pro-r34.8a8fd7b0-bl31-v1.45-ddr-v1.16.img.gz)



Thank you. I installed Python2 and built it here, and it worked.

Although the thread is already closed, the image you provided seems to be a broken image without ARM Trusted Firmware. Didn't you encounter any other errors during the build? There might be some errors occurring.

Here is the image I built that works, along with its log.
[rkloader-vendor-v2017.09-rk3588-orangepi_5_pro-r34.8a8fd7b0-bl31-v1.45-ddr-v1.16.img.gz](https://github.com/user-attachments/files/16430054/rkloader-vendor-v2017.09-rk3588-orangepi_5_pro-r34.8a8fd7b0-bl31-v1.45-ddr-v1.16.img.gz)

[build.log](https://github.com/user-attachments/files/16430059/build.log)

**Comment by 7Ji** [comment]
Sorry but I can't check the image as I don't have an 5pro.

Can you check the image on the [nightly release page](https://github.com/7Ji/orangepi5-rkloader/releases/tag/nightly)?

**Comment by Callyth** [comment]
OK, it seems to be working. When the ARM Trusted Firmware is included in the image, the size of the gz file is 796KB, but when it's not included, the size is 717KB. This difference is likely due to compression, where the absence of ATF allows for zeros to be represented with fewer bytes.
